targetScope = 'resourceGroup'

param location string
param accountName string
param projectName string
param deployChatModel bool
param deployEmbeddingModel bool
param chatDeploymentName string
param chatModelName string
param chatModelVersion string
param chatModelSku string
param chatModelCapacity int
param embeddingDeploymentName string
param embeddingModelName string
param embeddingModelVersion string
param embeddingModelSku string
param embeddingModelCapacity int
param tags object

resource account 'Microsoft.CognitiveServices/accounts@2025-06-01' existing = {
  name: accountName
}

resource project 'Microsoft.CognitiveServices/accounts/projects@2025-06-01' = {
  parent: account
  name: projectName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    displayName: projectName
    description: 'Generated by the governed AI application launchpad.'
  }
  tags: tags
}

resource chatModel 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = if (deployChatModel) {
  parent: account
  name: chatDeploymentName
  sku: {
    name: chatModelSku
    capacity: chatModelCapacity
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: chatModelName
      version: chatModelVersion
    }
    raiPolicyName: 'Microsoft.DefaultV2'
    versionUpgradeOption: 'OnceNewDefaultVersionAvailable'
  }
}

resource embeddingModel 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = if (deployEmbeddingModel) {
  parent: account
  name: embeddingDeploymentName
  dependsOn: [
    chatModel
  ]
  sku: {
    name: embeddingModelSku
    capacity: embeddingModelCapacity
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: embeddingModelName
      version: embeddingModelVersion
    }
    raiPolicyName: 'Microsoft.DefaultV2'
    versionUpgradeOption: 'OnceNewDefaultVersionAvailable'
  }
}

output projectName string = project.name
output projectResourceId string = project.id
output projectEndpoint string = 'https://${accountName}.services.ai.azure.com/api/projects/${project.name}'
output chatModelDeployment string = deployChatModel ? chatModel.name : ''
output chatModelResourceId string = deployChatModel ? chatModel.id : ''
output embeddingModelDeployment string = deployEmbeddingModel ? embeddingModel.name : ''
output embeddingModelResourceId string = deployEmbeddingModel ? embeddingModel.id : ''
