import { useCallback, useEffect, useMemo, useState } from 'react'
import './prototype.css'
import SolutionBuilder from './SolutionBuilder'
import CouncilWorkspace from './CouncilWorkspace'
import { getUseCase, getUseCases, type UseCaseRecord } from './api'

type Answer = 'yes' | 'no' | ''
type RiskLevel = 'Low' | 'Moderate' | 'High' | 'Restricted'
type View = 'dashboard' | 'applications' | 'agents' | 'lifecycle' | 'intake' | 'submitted' | 'solution' | 'council'
const portalViewKey='launchpad.portal-view'
const portalViews=new Set<View>(['dashboard','applications','agents','lifecycle','intake','submitted','solution','council'])

function restoredPortalView():View{
  try{
    const value=sessionStorage.getItem(portalViewKey) as View|null
    return value&&portalViews.has(value)?value:'dashboard'
  }catch{return'dashboard'}
}
type Form = {
  name:string; summary:string; unit:string; owner:string; audience:string; stage:string
  personal:Answer; health:Answer; employee:Answer; confidential:Answer; regulated:Answer
  identifiable:Answer; modelTraining:Answer; externalData:Answer; crossBorder:Answer
  capabilities:string[]; autonomy:number; publicFacing:Answer; safety:Answer; quality:Answer
  decisions:Answer; humanReview:Answer; audit:Answer
}
type Risk = {level:RiskLevel;score:number;dimensions:{name:string;value:number}[];reasons:string[];reviewers:string[];controls:string[]}
const initial:Form={name:'',summary:'',unit:'',owner:'',audience:'',stage:'',personal:'',health:'',employee:'',confidential:'',regulated:'',identifiable:'',modelTraining:'',externalData:'',crossBorder:'',capabilities:[],autonomy:1,publicFacing:'',safety:'',quality:'',decisions:'',humanReview:'',audit:''}
const stepNames=['Use case basics','Data profile','Modeling approach','Impact & controls','Review & submit']
const apps=[
  ['Commercial Content Assistant','AI-2026-0142','In review','Moderate','58%','Sep 8, 2026'],
  ['Quality Event Summarizer','AI-2026-0118','Approved','High','100%','Sep 5, 2026'],
  ['Supply Chain Knowledge Search','AI-2026-0097','Draft','Low','32%','Aug 29, 2026'],
]

export function ExperimentalDeveloperDashboard({start,configure}:{start:()=>void;configure:()=>void}){
  const [useCases,setUseCases]=useState<UseCaseRecord[]>([])
  const [loadError,setLoadError]=useState('')
  const [reviewRecord,setReviewRecord]=useState<UseCaseRecord|null>(null)
  useEffect(()=>{let active=true;void getUseCases().then(records=>{if(active)setUseCases(records)}).catch(error=>{if(active)setLoadError(error instanceof Error?error.message:'Synced GenAI use cases could not be loaded.')});return()=>{active=false}},[])
  const approved=useCases.filter(record=>record.status==='Approved')
  const inReview=useCases.filter(record=>record.status==='Awaiting Review')
  const currentStage=(record:UseCaseRecord)=>record.lifecycle.find(stage=>stage.key===record.currentStage)
  return <main className="axon-page developer-dashboard">
    <section className="developer-intro"><div><p className="axon-kicker">GOVERNED GENAI <i/> ML & DATA SCIENCE <i/> AZURE</p><h1>Your AI delivery workspace</h1><p>Follow imported GenAI council reviews, continue architecture after approval, and create new ML or Data Science use cases.</p></div><button className="primary" onClick={start}><Icon name="plus"/>New ML / Data Science Use Case</button></section>
    <section className="governance-boundary"><Icon name="shield"/><span><strong>GenAI use cases are submitted in the J&J Governance Portal</strong><small>Review records below are synchronized and read-only. Architecture unlocks only after council approval.</small></span><em>System of record</em></section>
    {loadError&&<section className="axon-sync-error"><Icon name="info"/>{loadError}</section>}
    <section className="axon-section axon-progress"><div className="axon-section-title"><div><p className="axon-kicker">APPROVED GENAI</p><h2>Continue where you left off</h2><p>Resume defining, validating, or deploying architecture for council-approved use cases.</p></div><span className="sync-label"><Icon name="check"/>Synced from Governance Portal</span></div><div className="axon-case-grid">{approved.map(record=><article key={record.id} className="ready"><div><h3>{record.name}</h3><Pill text="Approved" tone="Approved"/></div><small>{record.id} · {record.businessUnit}</small><p><b>{currentStage(record)?.label??'Architecture enablement'}</b><strong>{record.riskLevel} risk</strong></p><div className="axon-progress-bar"><i style={{width:'45%'}}/></div><small>Technical enablement in progress</small><div className="axon-update"><Icon name="check"/>Approval fields locked · architecture work available</div><footer><small>Synced {new Date(record.sourceUpdatedAt).toLocaleDateString()}</small><button onClick={configure}>Continue architecture <Icon name="arrow"/></button></footer></article>)}</div>{!loadError&&!approved.length&&<p className="axon-empty">No approved GenAI use cases are ready for architecture.</p>}</section>
    <section className="axon-section axon-review"><div className="axon-section-title"><div><p className="axon-kicker">GENAI COUNCIL PIPELINE</p><h2>Use cases in review</h2><p>Track review progress here. There are no architecture questions until approval.</p></div><span className="sync-label"><Icon name="shield"/>Read-only status</span></div><div className="axon-case-grid">{inReview.map(record=><article key={record.id}><div><h3>{record.name}</h3><Pill text="In review" tone="In review"/></div><small>{record.id} · {record.businessUnit}</small><p><b>{currentStage(record)?.label??'Council review'}</b><strong>{record.riskLevel} risk</strong></p><div className="axon-progress-bar"><i style={{width:'65%'}}/></div><small>Governance review in progress</small><div className="axon-update"><Icon name="info"/>No architecture action required</div><footer><small>Synced {new Date(record.sourceUpdatedAt).toLocaleDateString()}</small><button onClick={()=>setReviewRecord(record)}>View review status <Icon name="arrow"/></button></footer></article>)}</div></section>
    <section className="ml-entry"><div><p className="axon-kicker">LOCAL INTAKE</p><h2>Starting ML or Data Science work?</h2><p>Create and assess those use cases directly in this portal. GenAI submissions remain in the Governance Portal.</p></div><button className="primary" onClick={start}><Icon name="plus"/>New ML / Data Science Use Case</button></section>
    {reviewRecord&&<div className="review-status-backdrop" role="presentation" onClick={()=>setReviewRecord(null)}><section className="review-status-panel" role="dialog" aria-modal="true" aria-labelledby="review-status-title" onClick={event=>event.stopPropagation()}><header><span><small>SYNCED GENAI USE CASE</small><h2 id="review-status-title">{reviewRecord.name}</h2><p>{reviewRecord.id} · {reviewRecord.sourceSystem}</p></span><button aria-label="Close review status" onClick={()=>setReviewRecord(null)}>×</button></header><p>{reviewRecord.summary}</p><div className="review-status-meta"><span>Status<strong>{reviewRecord.status}</strong></span><span>Risk<strong>{reviewRecord.riskLevel}</strong></span><span>Business unit<strong>{reviewRecord.businessUnit}</strong></span></div><ol>{reviewRecord.lifecycle.slice(0,4).map(stage=><li className={stage.status} key={stage.key}><i>{stage.status==='complete'?'✓':stage.status==='current'?'●':'○'}</i><span><strong>{stage.label}</strong><small>{stage.owner}{stage.completedAt?` · ${new Date(stage.completedAt).toLocaleDateString()}`:''}</small></span></li>)}</ol><div className="review-lock"><Icon name="shield"/><span><strong>Architecture is locked during review</strong><small>It becomes available automatically after GenAI Council approval.</small></span></div></section></div>}
  </main>
}

const stageFor=(record:UseCaseRecord)=>record.lifecycle.find(stage=>stage.key===record.currentStage)??record.lifecycle.find(stage=>stage.status==='current')??record.lifecycle[record.lifecycle.length-1]
const statusFor=(record:UseCaseRecord)=>record.status==='Awaiting Review'?'Awaiting approval':['Approved','In Progress'].includes(record.status)?'In progress':record.status
const progressFor=(record:UseCaseRecord)=>{
  if(record.status==='Rejected')return 4
  if(record.status==='Completed')return 100
  const stageProgress:Record<string,number>={
    submit:4,'coe-review':8,governance:12,decision:12,approved:16,
    'data-knowledge':24,'tools-agents':34,channels:43,'memory-state':52,
    architecture:62,'access-governance':71,'model-capacity':80,
    'region-readiness':88,'infrastructure-deploy':94,production:100,
  }
  return stageProgress[record.currentStage]??8
}

function DeveloperDashboard({start,configure,explore,agents}:{start:()=>void;configure:(applicationId:string)=>void;explore:()=>void;agents:()=>void}){
  const [useCases,setUseCases]=useState<UseCaseRecord[]>([])
  const [loadError,setLoadError]=useState('')
  useEffect(()=>{let active=true;void getUseCases().then(records=>{if(active)setUseCases(records)}).catch(error=>{if(active)setLoadError(error instanceof Error?error.message:'Synced GenAI use cases could not be loaded.')});return()=>{active=false}},[])
  const active=useCases.filter(record=>record.approvedAt&&record.status!=='Completed'&&record.status!=='Rejected')
  const inReview=useCases.filter(record=>record.status==='Awaiting Review')
  const stages=[
    ['Govern','Submitted in the J&J Governance Portal','shield'],
    ['Approve','Reviewed by the GenAI Council','check'],
    ['Define','Confirm data, models, and architecture','grid'],
    ['Validate','Review policy, quota, cost, and what-if','check'],
    ['Deploy','Provision approved Azure infrastructure','arrow'],
    ['Operate','Monitor the environment and evidence','spark'],
  ]
  return <main className="axon-page">
    <section className="axon-hero">
      <div className="axon-hero-copy">
        <p className="axon-kicker">PEOPLE <i/> GOVERNANCE <i/> TECHNOLOGY <i/> IMPACT</p>
        <h1>Move Approved AI<br/>Into a <em>Real<br/>Solution</em></h1>
        <p className="axon-lede">Follow GenAI council reviews, continue architecture after approval, and deploy governed Azure infrastructure through one connected experience.</p>
        <div className="axon-actions"><button className="primary" onClick={start}><Icon name="plus"/>New ML / Data Science Use Case</button><button className="secondary" onClick={agents}><Icon name="grid"/>MedTech Agent Catalog</button><button className="secondary" onClick={explore}>Explore Use Cases</button></div>
        {active[0]&&<button className="axon-draft" onClick={()=>configure(active[0].id)}><i><Icon name="grid"/></i><span><small>CONTINUE {stageFor(active[0])?.label.toUpperCase()}</small><strong>{active[0].name}</strong><small>{active[0].id} · {statusFor(active[0])} · {progressFor(active[0])}% complete</small></span><b>Continue <Icon name="arrow"/></b></button>}
      </div>
      <div className="axon-hero-image"><img src="https://basic-truce-77814857.figma.site/assets/gray_f-GzwqIGYV.png" alt="Medical professional reviewing AI-assisted insights"/><div className="axon-values"><span><Icon name="spark"/>Ideas to Impact</span><span><Icon name="shield"/>Responsible by Design</span><span><Icon name="grid"/>Built Together</span><span><Icon name="arrow"/>Real Outcomes</span></div></div>
    </section>
    {loadError&&<section className="axon-section"><div className="deferred-note"><Icon name="info"/><div><strong>Governance sync unavailable</strong><span>{loadError}</span></div></div></section>}
    <section className="axon-section axon-progress">
      <div className="axon-section-title"><div><h2>Continue Where You Left Off</h2><p>Resume defining and deploying architecture for approved GenAI use cases.</p></div><button onClick={explore}>View All Use Cases <Icon name="arrow"/></button></div>
      <div className="axon-case-grid">{active.map(record=>{const stage=stageFor(record);const progress=progressFor(record);const status=statusFor(record);return <article className="ready" key={record.id}><div><h3>{record.name}</h3><Pill text={status} tone={status}/></div><small>{record.id} · {record.businessUnit}</small><p><b>{stage?.label??'Infrastructure buildout'}</b><strong>{progress}%</strong></p><div className="axon-progress-bar"><i style={{width:`${progress}%`}}/></div><small>Continue {stage?.label??'infrastructure buildout'}</small><div className="axon-update"><Icon name="check"/>Governance approved — use case fields are locked</div><footer><small>Synced {new Date(record.sourceUpdatedAt).toLocaleDateString()}</small><button onClick={()=>configure(record.id)}>Continue <Icon name="arrow"/></button></footer></article>})}</div>
    </section>
    <section className="axon-section axon-explore">
      <div className="axon-section-title"><div><p className="axon-kicker">GENAI COUNCIL PIPELINE</p><h2>Use cases in review</h2><p>Synced from the J&J Governance Portal. No architecture action is available until approval.</p></div><button>Open Governance Portal <Icon name="arrow"/></button></div>
      <div className="axon-example-grid">{inReview.map((record,index)=><article key={record.id}><span>0{index+1}</span><div><small>{record.id} · {record.businessUnit}</small><h3>{record.name}</h3><p>{record.summary}</p><div className="axon-update"><Icon name="shield"/>GenAI Council review · Read only</div></div><Icon name="arrow"/></article>)}</div>
    </section>
    <section className="axon-journey"><div><p className="axon-kicker">FROM APPROVAL TO PRODUCTION</p><h2>One connected path to real impact.</h2><p>Governance remains authoritative while this portal turns approved use cases into secure, deployable architecture.</p></div><div className="axon-stages">{stages.map((stage,index)=><article key={stage[0]}><b>0{index+1}</b><span><Icon name={stage[2]}/></span><h3>{stage[0]}</h3><p>{stage[1]}</p></article>)}</div></section>
    <section className="axon-cta"><div><p className="axon-kicker">START HERE</p><h2>Have an ML or Data Science idea?</h2><p>Create it here. New GenAI applications begin in the J&J Governance Portal.</p></div><button className="primary" onClick={start}><Icon name="plus"/>New ML / Data Science Use Case</button></section>
  </main>
}

type CatalogAgent={id:string;name:string;summary:string;owner:string;businessUnit:string;endpoint:string;hosting?:string;region:string;version:string;status:'Production'|'Maintenance';updated:string;tokenUsage30d?:number}
const catalogStorageKey='launchpad.agent-catalog'
const seededAgents:CatalogAgent[]=[
  {id:'AGT-1042',name:'Global Terminology Resolver',summary:'Normalizes medical and product terminology against approved enterprise vocabularies.',owner:'Enterprise Language Services',businessUnit:'Enterprise',endpoint:'https://agents.mt-axon.example/v1/terminology',hosting:'Microsoft Foundry',region:'East US 2',version:'v2.4.1',status:'Production',updated:'2026-09-14',tokenUsage30d:2410000},
  {id:'AGT-1036',name:'Sensitive Data Redaction Agent',summary:'Detects and redacts personal, health, and confidential data before downstream processing.',owner:'Privacy Engineering',businessUnit:'MedTech Quality',endpoint:'https://agents.mt-axon.example/v1/redaction',hosting:'Azure Kubernetes Service',region:'East US 2',version:'v1.8.0',status:'Production',updated:'2026-09-11',tokenUsage30d:1840000},
  {id:'AGT-1029',name:'Enterprise Document Classifier',summary:'Assigns governed document types, sensitivity labels, and retention categories.',owner:'Information Lifecycle Services',businessUnit:'Enterprise',endpoint:'https://agents.mt-axon.example/v1/classification',hosting:'Azure Container Apps',region:'Central US',version:'v3.1.2',status:'Production',updated:'2026-09-08',tokenUsage30d:3260000},
  {id:'AGT-1021',name:'Workflow Triage Router',summary:'Routes incoming work to the correct queue using urgency, topic, and ownership signals.',owner:'Automation Platform',businessUnit:'Supply Chain',endpoint:'https://agents.mt-axon.example/v1/triage',hosting:'Microsoft Foundry',region:'East US 2',version:'v2.0.6',status:'Production',updated:'2026-09-05',tokenUsage30d:842000},
  {id:'AGT-1014',name:'Multilingual Response Validator',summary:'Evaluates translated responses for meaning preservation, terminology, and tone.',owner:'Global Experience Engineering',businessUnit:'Commercial',endpoint:'https://agents.mt-axon.example/v1/translation-validation',hosting:'Azure App Service',region:'West US 3',version:'v1.5.3',status:'Production',updated:'2026-08-29',tokenUsage30d:1170000},
  {id:'AGT-1008',name:'Audit Evidence Packager',summary:'Collects runtime traces, model metadata, and approvals into review-ready evidence bundles.',owner:'Responsible AI Operations',businessUnit:'Research',endpoint:'https://agents.mt-axon.example/v1/audit-packaging',hosting:'Azure Container Apps',region:'East US 2',version:'v1.9.4',status:'Maintenance',updated:'2026-08-22',tokenUsage30d:394000},
]
function formatTokenUsage(agent:CatalogAgent){const seed=[...`${agent.id}${agent.name}`].reduce((total,character)=>total+character.charCodeAt(0),0);const value=agent.tokenUsage30d??300000+(seed*7919)%3000000;if(value>=1000000)return`${(value/1000000).toFixed(2).replace(/\.0+$|0$/,'')}M`;if(value>=1000)return`${Math.round(value/1000)}K`;return value.toLocaleString()}
function restoredAgents(){try{const saved=JSON.parse(localStorage.getItem(catalogStorageKey)??'[]');return Array.isArray(saved)?[...saved,...seededAgents] as CatalogAgent[]:seededAgents}catch{return seededAgents}}
function AgentCatalog({home}:{home:()=>void}){
  const [agents,setAgents]=useState<CatalogAgent[]>(restoredAgents)
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState('All')
  const [registering,setRegistering]=useState(false)
  const [registered,setRegistered]=useState('')
  const [error,setError]=useState('')
  const [form,setForm]=useState({name:'',summary:'',owner:'',businessUnit:'Enterprise',endpoint:'',hosting:'Microsoft Foundry',region:'East US 2',version:'v1.0.0'})
  const visible=agents.filter(agent=>{const term=query.trim().toLowerCase();return(!term||`${agent.name} ${agent.id} ${agent.owner} ${agent.businessUnit}`.toLowerCase().includes(term))&&(status==='All'||agent.status===status)})
  const update=(field:keyof typeof form,value:string)=>setForm(current=>({...current,[field]:value}))
  const close=()=>{setRegistering(false);setError('')}
  const register=(event:React.FormEvent)=>{
    event.preventDefault()
    let endpoint:URL
    try{endpoint=new URL(form.endpoint)}catch{setError('Enter a valid agent endpoint URL.');return}
    if(endpoint.protocol!=='https:'){setError('The agent endpoint must use HTTPS.');return}
    const agent:CatalogAgent={...form,id:`AGT-${String(1100+agents.length+1).padStart(4,'0')}`,endpoint:endpoint.toString().replace(/\/$/,''),status:'Production',updated:new Date().toISOString().slice(0,10)}
    setAgents(current=>[agent,...current])
    try{const saved=JSON.parse(localStorage.getItem(catalogStorageKey)??'[]');localStorage.setItem(catalogStorageKey,JSON.stringify([agent,...(Array.isArray(saved)?saved:[])]))}catch{/* The current session still retains the registration. */}
    setRegistered(agent.name)
    setForm({name:'',summary:'',owner:'',businessUnit:'Enterprise',endpoint:'',hosting:'Microsoft Foundry',region:'East US 2',version:'v1.0.0'})
    close()
  }
  return <main className="agent-catalog">
    <nav className="inventory-breadcrumb" aria-label="Breadcrumb"><button onClick={home}><Icon name="back"/>Back to home</button><Icon name="arrow"/><strong>MedTech Agent Catalog</strong></nav>
    <section className="agent-catalog-heading"><div><p className="axon-kicker">PRODUCTION AI SERVICES</p><h1>MedTech Agent Catalog</h1><p className="agent-catalog-attribution">Powered by Enterprise Agent Catalog</p><p className="agent-catalog-intro">Teams can register and manage agents from any platform, whether built in Microsoft Foundry or elsewhere.</p></div><button className="primary" onClick={()=>setRegistering(true)}><Icon name="plus"/>Register agent</button></section>
    {registered&&<div className="agent-registered" role="status"><Icon name="check"/><span><strong>{registered} is registered</strong><small>The agent is now listed in the production catalog.</small></span><button aria-label="Dismiss" onClick={()=>setRegistered('')}>×</button></div>}
    <section className="agent-catalog-stats"><div><strong>{agents.filter(agent=>agent.status==='Production').length}</strong><span>Production agents</span></div><div><strong>{new Set(agents.map(agent=>agent.businessUnit)).size}</strong><span>Business units</span></div><div><strong>{new Set(agents.map(agent=>agent.region)).size}</strong><span>Azure regions</span></div><div><strong>99.94%</strong><span>Catalog availability</span></div></section>
    <section className="agent-catalog-table">
      <div className="agent-catalog-tools"><label><Icon name="search"/><input aria-label="Search agents" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search agents, owners, or IDs..."/></label><select aria-label="Filter agents by status" value={status} onChange={event=>setStatus(event.target.value)}><option>All</option><option>Production</option><option>Maintenance</option></select><span>{visible.length} agents</span></div>
      <div className="agent-table-scroll"><table><thead><tr><th>Agent</th><th>Owner</th><th>Agent endpoint</th><th>Hosting platform</th><th>Region</th><th>Version</th><th>Status</th><th>Last updated</th><th>Token usage (30d)</th></tr></thead><tbody>{visible.map(agent=>{const endpoint=new URL(agent.endpoint);return <tr key={agent.id}><td><strong>{agent.name}</strong><small>{agent.id} · {agent.businessUnit}</small><p>{agent.summary}</p></td><td>{agent.owner}</td><td><a href={agent.endpoint} target="_blank" rel="noreferrer">{endpoint.hostname}{endpoint.pathname==='/'?'':endpoint.pathname}<Icon name="arrow"/></a></td><td>{agent.hosting??'Azure Container Apps'}</td><td>{agent.region}</td><td><code>{agent.version}</code></td><td><span className={`agent-status ${agent.status.toLowerCase()}`}><i/>{agent.status}</span></td><td>{new Date(agent.updated).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</td><td><strong>{formatTokenUsage(agent)}</strong></td></tr>})}</tbody></table>{!visible.length&&<div className="inventory-empty"><strong>No matching agents</strong><span>Adjust your search or status filter.</span></div>}</div>
    </section>
    {registering&&<div className="agent-register-backdrop" onClick={close}><form className="agent-register" onSubmit={register} onClick={event=>event.stopPropagation()}><header><div><small>PRODUCTION REGISTRY</small><h2>Register an agent</h2><p>Add an existing production agent to the catalog.</p></div><button type="button" aria-label="Close registration" onClick={close}>×</button></header><div className="agent-register-fields"><label>Agent name<input required value={form.name} onChange={event=>update('name',event.target.value)} placeholder="e.g. Medical Information Assistant"/></label><label>Owning team<input required value={form.owner} onChange={event=>update('owner',event.target.value)} placeholder="Team or product owner"/></label><label className="full">Description<textarea required value={form.summary} onChange={event=>update('summary',event.target.value)} placeholder="What does this agent do in production?"/></label><label className="full">Agent endpoint URL<input required type="url" value={form.endpoint} onChange={event=>{update('endpoint',event.target.value);setError('')}} placeholder="https://agents.example.com/v1/my-agent"/><small>Enter the HTTPS invocation or gateway endpoint exposed to approved consumers.</small></label><label>Hosting platform<select value={form.hosting} onChange={event=>update('hosting',event.target.value)}><option>Microsoft Foundry</option><option>Azure Container Apps</option><option>Azure Kubernetes Service</option><option>Azure App Service</option><option>External managed service</option></select></label><label>Business unit<select value={form.businessUnit} onChange={event=>update('businessUnit',event.target.value)}><option>Enterprise</option><option>Commercial</option><option>MedTech Quality</option><option>Research</option><option>Supply Chain</option></select></label><label>Azure region<select value={form.region} onChange={event=>update('region',event.target.value)}><option>East US 2</option><option>Central US</option><option>West US 3</option><option>North Europe</option></select></label><label>Release version<input required value={form.version} onChange={event=>update('version',event.target.value)} placeholder="v1.0.0"/></label></div>{error&&<p className="agent-register-error"><Icon name="info"/>{error}</p>}<footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><Icon name="plus"/>Register agent</button></footer></form></div>}
  </main>
}

const businessFunctions:Record<string,string>={Commercial:'Marketing','MedTech Quality':'Quality & Compliance','Enterprise':'Enterprise Technology','Supply Chain':'Supply Chain','Research':'R&D'}
function UseCaseInventory({home,start,configure}:{home:()=>void;start:()=>void;configure:(applicationId:string)=>void}){
  const [records,setRecords]=useState<UseCaseRecord[]>([])
  const [query,setQuery]=useState('')
  const [statusFilter,setStatusFilter]=useState('All')
  const [stageFilter,setStageFilter]=useState('All')
  const [sort,setSort]=useState('updated')
  const [selected,setSelected]=useState<UseCaseRecord|null>(null)
  const [loadError,setLoadError]=useState('')
  useEffect(()=>{let active=true;void getUseCases().then(items=>{if(active)setRecords(items)}).catch(error=>{if(active)setLoadError(error instanceof Error?error.message:'Use cases could not be loaded.')});return()=>{active=false}},[])
  const statuses=['All',...new Set(records.map(statusFor))]
  const stages=['All',...new Set(records.map(record=>stageFor(record)?.label??'Not started'))]
  const counts={
    total:records.length,
    awaiting:records.filter(record=>record.status==='Awaiting Review').length,
    progress:records.filter(record=>['Approved','In Progress'].includes(record.status)).length,
    completed:records.filter(record=>record.status==='Completed').length,
    action:records.filter(record=>['Rejected','Blocked'].includes(record.status)).length,
  }
  const visible=records.filter(record=>{
    const term=query.trim().toLowerCase()
    return(!term||`${record.name} ${record.id} ${record.businessUnit}`.toLowerCase().includes(term))&&(statusFilter==='All'||statusFor(record)===statusFilter)&&(stageFilter==='All'||stageFor(record)?.label===stageFilter)
  }).sort((left,right)=>sort==='name'?left.name.localeCompare(right.name):Date.parse(right.sourceUpdatedAt)-Date.parse(left.sourceUpdatedAt))
  const toneFor=(status:string)=>status.toLowerCase().replaceAll(' ','-')
  return <main className="use-case-inventory">
    <nav className="inventory-breadcrumb" aria-label="Breadcrumb"><button onClick={home}><Icon name="back"/>Back to home</button><Icon name="arrow"/><strong>My Use Cases</strong></nav>
    <section className="inventory-heading"><div><p className="axon-kicker">AI DELIVERY PORTFOLIO</p><h1>My Use Cases</h1><p>View and track imported GenAI use cases and locally created ML or Data Science work.</p></div><button className="primary" onClick={start}><Icon name="plus"/>New ML / Data Science Use Case</button></section>
    <section className="inventory-summary" aria-label="Use case summary"><div><b>{counts.total}</b><span>Total use cases</span></div><div><b>{counts.awaiting}</b><span>Awaiting approval</span></div><div><b>{counts.progress}</b><span>In progress</span></div><div><b>{counts.completed}</b><span>Completed</span></div><div><b>{counts.action}</b><span>Action required</span></div></section>
    <section className="inventory-card">
      <div className="inventory-tools"><label className="inventory-search"><Icon name="search"/><input aria-label="Search use cases" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search use cases..."/></label><span>Filter:</span><select aria-label="Filter by status" value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select><select aria-label="Filter by stage" value={stageFilter} onChange={event=>setStageFilter(event.target.value)}>{stages.map(stage=><option key={stage}>{stage}</option>)}</select><i/><span>Sort:</span><select aria-label="Sort use cases" value={sort} onChange={event=>setSort(event.target.value)}><option value="updated">Last Updated</option><option value="name">Use Case Name</option></select><small>Showing {visible.length} of {records.length}</small></div>
      {loadError?<div className="inventory-empty"><Icon name="info"/><strong>Use cases unavailable</strong><span>{loadError}</span></div>:<div className="inventory-table"><table><thead><tr><th>Use case</th><th>Use case ID</th><th>Business unit</th><th>Function</th><th>Current stage</th><th>Status</th><th>Next action</th><th>Last updated</th><th>Action</th></tr></thead><tbody>{visible.map(record=>{const stage=stageFor(record);const status=statusFor(record);const progress=progressFor(record);const canConfigure=record.approvedAt&&record.status!=='Completed'&&record.status!=='Rejected';return <tr key={record.id}><td><strong>{record.name}</strong><small>{record.sourceSystem}</small></td><td><code>{record.id}</code></td><td>{record.businessUnit}</td><td>{businessFunctions[record.businessUnit]??record.businessUnit}</td><td><span>{stage?.label??'Not started'}</span><div className="use-case-progress"><i style={{width:`${progress}%`}}/></div></td><td><span className={`inventory-status ${toneFor(status)}`}><i/>{status}</span></td><td className={record.status==='Rejected'?'rejected-action':''}>{record.status==='Awaiting Review'?'Awaiting GenAI Council decision':record.status==='Rejected'?'Review rejection reason':record.status==='Completed'?'No action required':`Continue ${stage?.label??'infrastructure buildout'}`}</td><td>{new Date(record.sourceUpdatedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</td><td><button className={canConfigure?'continue-action':''} onClick={()=>canConfigure?configure(record.id):setSelected(record)}>{canConfigure?'Continue':'View'} <Icon name="arrow"/></button></td></tr>})}</tbody></table>{!visible.length&&<div className="inventory-empty"><strong>No matching use cases</strong><span>Adjust the search or filters.</span></div>}</div>}
      <footer className="inventory-footer"><span>{visible.length} results</span><div><button disabled><Icon name="back"/></button><button className="active">1</button><button disabled><Icon name="arrow"/></button></div></footer>
    </section>
    {selected&&<div className="inventory-modal-backdrop" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-labelledby="use-case-detail-title" onClick={event=>event.stopPropagation()}><header><div><small>{selected.id} · {selected.sourceSystem}</small><h2 id="use-case-detail-title">{selected.name}</h2></div><button aria-label="Close" onClick={()=>setSelected(null)}>×</button></header><span className={`inventory-status ${toneFor(statusFor(selected))}`}><i/>{statusFor(selected)}</span><p>{selected.summary}</p><dl><div><dt>Current stage</dt><dd>{stageFor(selected)?.label}</dd></div><div><dt>Business unit</dt><dd>{selected.businessUnit}</dd></div><div><dt>Risk</dt><dd>{selected.riskLevel}</dd></div><div><dt>Next action</dt><dd>{selected.status==='Rejected'?'Review the decision in the Governance Portal':'No action is available in this portal yet'}</dd></div></dl></section></div>}
  </main>
}

type EmbeddedWorkspaceScreen='overview'|'definition'|'design'|'describe'|'data'|'connectors'|'channels'|'memory'|'requirements'|'governance'|'model'|'region'|'architecture'|'iac'|'provisioning'|'activity'
const workspaceByStage:Record<string,EmbeddedWorkspaceScreen>={submit:'definition','coe-review':'definition',governance:'definition',approved:'definition','data-knowledge':'data','tools-agents':'connectors',channels:'channels','memory-state':'memory',architecture:'requirements','access-governance':'governance','model-capacity':'model','region-readiness':'region','infrastructure-deploy':'provisioning',production:'activity'}
const stageByWorkspace:Record<EmbeddedWorkspaceScreen,string>={overview:'approved',definition:'approved',design:'approved',describe:'approved',data:'data-knowledge',connectors:'tools-agents',channels:'channels',memory:'memory-state',requirements:'architecture',governance:'access-governance',model:'model-capacity',region:'region-readiness',architecture:'region-readiness',iac:'infrastructure-deploy',provisioning:'infrastructure-deploy',activity:'production'}
function LifecycleDetail({applicationId,back}:{applicationId:string;back:()=>void}){
  const [record,setRecord]=useState<UseCaseRecord|null>(null)
  const [error,setError]=useState('')
  const [workspaceScreen,setWorkspaceScreen]=useState<EmbeddedWorkspaceScreen>('overview')
  const syncWorkspaceScreen=useCallback((screen:string)=>{if(screen in stageByWorkspace)setWorkspaceScreen(screen as EmbeddedWorkspaceScreen)},[])
  useEffect(()=>{let active=true;void getUseCase(applicationId).then(item=>{if(active){setWorkspaceScreen(workspaceByStage[item.currentStage]??'overview');setRecord(item)}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Use case could not be loaded.')});return()=>{active=false}},[applicationId])
  if(error)return <main className="lifecycle-page lifecycle-message"><Icon name="info"/><h1>Use case unavailable</h1><p>{error}</p><button onClick={back}>Back to My Use Cases</button></main>
  if(!record)return <main className="lifecycle-page lifecycle-message"><p>Loading lifecycle...</p></main>
  const current=stageFor(record)
  const approvedStageIndex=record.lifecycle.findIndex(stage=>stage.key==='approved')
  const governanceStageIndex=record.lifecycle.findIndex(stage=>stage.key==='governance')
  const importedDeliveryLifecycle=approvedStageIndex>=0?record.lifecycle.slice(approvedStageIndex):governanceStageIndex>=0?[{...record.lifecycle[governanceStageIndex],key:'approved',label:'Approved'},...record.lifecycle.slice(governanceStageIndex+1)]:record.lifecycle
  const deliveryLifecycle=importedDeliveryLifecycle.filter(stage=>stage.key!=='access-governance')
  const activeStageKey=stageByWorkspace[workspaceScreen]
  const activeStageIndex=deliveryLifecycle.findIndex(stage=>stage.key===activeStageKey)
  const activeLabel=activeStageKey==='approved'?'Approved':activeStageKey==='architecture'?'Operating Requirements':record.lifecycle.find(stage=>stage.key===activeStageKey)?.label??current?.label??'Overview'
  return <main className="lifecycle-page">
    <nav className="lifecycle-breadcrumb"><button onClick={back}><Icon name="back"/>My Use Cases</button><Icon name="arrow"/><strong>{record.name}</strong></nav>
    <section className="lifecycle-title"><div><p className="axon-kicker">APPROVED USE CASE · {record.id}</p><h1>{record.name}</h1><p>{record.summary}</p></div><div><span className="inventory-status in-progress"><i/>In progress</span></div></section>
    <section className="lifecycle-pipeline"><header><h2>Delivery Lifecycle</h2></header><div>{deliveryLifecycle.map((stage,index)=>{const target=workspaceByStage[stage.key];const displayStatus=index<activeStageIndex?'complete':index===activeStageIndex?'current':'pending';return <article className={`${displayStatus} ${index===activeStageIndex?'selected':''}`} key={stage.key}><button disabled={!target} onClick={()=>target&&setWorkspaceScreen(target)}><span>{displayStatus==='complete'?<Icon name="check"/>:index+1}</span><strong>{index===0?'Approved':stage.key==='architecture'?'Operating Requirements':stage.label}</strong><small>{displayStatus==='complete'?(stage.completedAt?new Date(stage.completedAt).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'Complete'):displayStatus==='current'?'In progress':'—'}</small></button>{index<deliveryLifecycle.length-1&&<i/>}</article>})}</div></section>
    <div className="lifecycle-detail-grid">
      <section className="current-stage-card lifecycle-work-area"><header><div><small>CURRENT STAGE</small><h2>{activeLabel}</h2></div></header><div className="embedded-builder"><SolutionBuilder applicationId={record.id} exit={back} requestedScreen={workspaceScreen} onScreenChange={syncWorkspaceScreen}/></div></section>
    </div>
  </main>
}
function calculate(f:Form):Risk{
  let data=0,impact=0,exposure=0,regulatory=0
  const reasons:string[]=[],controls:string[]=[]
  const reviewers=new Set(['Business owner','AI Governance'])
  if(f.personal==='yes'){data+=35;reviewers.add('Privacy');reasons.push('Personal information will be processed')}
  if(f.health==='yes'){data+=55;regulatory+=40;reviewers.add('Privacy');reviewers.add('Health Care Compliance');reasons.push('Patient or health information is in scope')}
  if(f.employee==='yes'){data+=25;reviewers.add('Privacy');reasons.push('Employee information will be processed')}
  if(f.confidential==='yes'){data+=25;reviewers.add('Information Security');reasons.push('Confidential J&J information will be used')}
  if(f.regulated==='yes'){data+=30;regulatory+=45;reviewers.add('MedTech Quality');reasons.push('Regulated quality or clinical data is in scope')}
  if(f.identifiable==='yes'&&(f.personal==='yes'||f.health==='yes')){data+=20;reasons.push('Sensitive information may be directly identifiable')}
  if(f.modelTraining==='yes'){data+=25;reviewers.add('Privacy');reviewers.add('Responsible AI');controls.push('Define training-data use, retention, and deletion controls')}
  if(f.externalData==='yes'){exposure+=45;reviewers.add('Information Security');controls.push('Document data residency and transfer safeguards')}
  if(f.crossBorder==='yes'){exposure+=25;reviewers.add('Privacy');controls.push('Complete cross-border data transfer assessment')}
  if(f.publicFacing==='yes'){exposure+=45;reviewers.add('Responsible AI');reasons.push('The experience will be externally accessible')}
  if(f.safety==='yes'){impact+=75;regulatory+=50;reviewers.add('MedTech Quality');reasons.push('Incorrect output could affect patient safety')}
  if(f.quality==='yes'){impact+=50;regulatory+=40;reviewers.add('MedTech Quality');reasons.push('Output may influence product quality')}
  if(f.decisions==='yes'){impact+=40;reviewers.add('Responsible AI');reasons.push('AI may influence a consequential decision')}
  if(f.autonomy>=4){reviewers.add('Enterprise Architecture');reviewers.add('Responsible AI');reasons.push('The application can act in connected systems')}
  if(f.capabilities.includes('Execute actions'))reviewers.add('Information Security')
  if(f.humanReview==='yes')impact=Math.max(0,impact-15)
  if(f.humanReview==='no'&&f.autonomy>=3)controls.push('Add human review before consequential actions')
  if(f.audit==='no')controls.push('Enable prompt, output, and action audit logging')
  const dimensions=[{name:'Data sensitivity',value:Math.min(100,data)},{name:'AI autonomy',value:f.autonomy*18},{name:'Business impact',value:Math.min(100,impact)},{name:'External exposure',value:Math.min(100,exposure)},{name:'Regulatory relevance',value:Math.min(100,regulatory)}]
  const max=Math.max(...dimensions.map(d=>d.value)),avg=dimensions.reduce((a,d)=>a+d.value,0)/5
  const score=Math.round(max*.65+avg*.35)
  const level:RiskLevel=score>=75?'Restricted':score>=50?'High':score>=22?'Moderate':'Low'
  if(!reasons.length)reasons.push('No elevated risk indicators selected yet')
  return{level,score,dimensions,reasons,reviewers:[...reviewers],controls}
}
function Icon({name}:{name:string}){const p:Record<string,React.ReactNode>={grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,plus:<path d="M12 5v14M5 12h14"/>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/><path d="m9 12 2 2 4-4"/></>,arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>,back:<><path d="M19 12H5M11 18l-6-6 6-6"/></>,check:<path d="m5 12 4 4L19 6"/>,save:<><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 012 2"/><path d="M17 21v-8H7v8M7 3v5h8"/></>,info:<><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></>,data:<><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14c0 1.7 4 3 9 3s9-1.3 9-3V5M3 12c0 1.7 4 3 9 3s9-1.3 9-3"/></>,spark:<><path d="m12 3-1.7 4.3L6 9l4.3 1.7L12 15l1.7-4.3L18 9l-4.3-1.7L12 3z"/><path d="m5 16-.8 2.2L2 19l2.2.8L5 22l.8-2.2L8 19l-2.2-.8L5 16z"/></>};return <svg className="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
function Pill({text,tone}:{text:string;tone:string}){return <span className={`pill ${tone.toLowerCase().replace(' ','-')}`}>{text}</span>}
function Header({home,applications,active}:{home:()=>void;applications:()=>void;active:'developer'|'applications'|'council'}){
  return <header>
    <button className="brand" onClick={home}><span><strong>MT-AXON</strong><small>AI Launchpad</small></span></button>
    <nav><button className={active==='developer'?'active':''} onClick={home}>Home</button><button className={active==='applications'?'active':''} onClick={applications}>My Use Cases</button></nav>
    <div className="profile"><div><small>User type</small><strong>{active==='council'?'Council member':'Developer'}</strong></div><span>{active==='council'?'GC':'NB'}</span></div>
  </header>
}
export function LegacyConfigurationDashboard({start,configure}:{start:()=>void;configure:()=>void}){
  const stages=['Define','Govern','Enable','Build','Integrate','Go live']
  const examples=[['Clinical insights','Summarize clinical data, surface safety signals, and accelerate reporting.','MedTech · R&D'],['Knowledge assistant','Give teams trusted answers from internal policies, SOPs, and repositories.','Enterprise · People'],['Process automation','Automate document-heavy workflows across finance, procurement, and compliance.','Operations · Finance']]
  return <main className="axon-page">
    <section className="axon-hero">
      <div className="axon-hero-copy"><p className="axon-kicker">PEOPLE <i/> GOVERNANCE <i/> TECHNOLOGY <i/> IMPACT</p><h1>Turn Your AI Idea<br/>Into a <em>Real<br/>Solution</em></h1><p className="axon-lede">From idea and governance to build, integration and production — track your AI use case through one connected experience.</p><div className="axon-actions"><button className="primary" onClick={start}><Icon name="plus"/>Start New Use Case</button><button className="secondary">Explore Use Cases</button></div><button className="axon-draft" onClick={start}><i><Icon name="save"/></i><span><small>YOU HAVE A DRAFT WAITING</small><strong>Clinical Trial Insight Copilot</strong><small>Draft · Data Sources · Last edited 2 hours ago</small></span><b>Continue Editing <Icon name="arrow"/></b></button></div>
      <div className="axon-hero-image"><img src="https://basic-truce-77814857.figma.site/assets/gray_f-GzwqIGYV.png" alt="Medical professional reviewing AI-assisted imaging"/><div className="axon-values"><span><Icon name="spark"/>Ideas to Impact</span><span><Icon name="shield"/>Responsible by Design</span><span><Icon name="grid"/>Built Together</span><span><Icon name="arrow"/>Real Outcomes</span></div></div>
    </section>
    <section className="axon-section axon-progress"><div className="axon-section-title"><div><h2>Continue Where You Left Off</h2><p>Your active use cases and where each stands right now.</p></div><button>View All Use Cases <Icon name="arrow"/></button></div><div className="axon-case-grid">{apps.map((app,index)=><article key={app[1]} className={app[2]==='Approved'?'ready':''}><div><h3>{app[0]}</h3><Pill text={app[2]} tone={app[2]}/></div><small>{app[1]} · {index===0?'Commercial':index===1?'Quality & Compliance':'Enterprise Ops'}</small><p><b>{index===0?'AI COE Review':index===1?'Ready to configure':'Discovery'}</b><strong>{app[4]}</strong></p><div className="axon-progress-bar"><i style={{width:app[4]}}/></div><small>Stage {index===1?'9':index===0?'5':'3'} of 9</small><div className="axon-update"><Icon name={index===1?'check':'info'}/>{index===1?'Governance approved — configure your solution':index===0?'Review in progress — no action required':'Draft ready to continue'}</div><footer><small>Updated {app[5]}</small><button onClick={app[2]==='Approved'?configure:start}>{app[2]==='Approved'?'Configure':'View Lifecycle'} <Icon name="arrow"/></button></footer></article>)}</div></section>
    <section className="axon-section axon-explore"><div className="axon-section-title"><div><p className="axon-kicker">EXPLORE THE POSSIBILITIES</p><h2>AI use cases across the business</h2></div><button>Explore All Use Cases <Icon name="arrow"/></button></div><div className="axon-example-grid">{examples.map((example,index)=><article key={example[0]}><span>0{index+1}</span><div><small>{example[2]}</small><h3>{example[0]}</h3><p>{example[1]}</p></div><Icon name="arrow"/></article>)}</div></section>
    <section className="axon-journey"><div><p className="axon-kicker">FROM IDEA TO PRODUCTION</p><h2>One connected path to real impact.</h2><p>Every use case moves through the same transparent, governed journey — with the right teams alongside you.</p></div><div className="axon-stages">{stages.map((stage,index)=><article key={stage}><b>0{index+1}</b><span><Icon name={index===1?'shield':index===5?'check':'arrow'}/></span><h3>{stage}</h3><p>{['Describe the opportunity','Assess risk and controls','Access tools and data','Develop with support','Connect your systems','Launch and measure'][index]}</p></article>)}</div></section>
    <section className="axon-cta"><div><p className="axon-kicker">READY WHEN YOU ARE</p><h2>Have an AI idea?</h2><p>Turn it into a governed AI solution with AI Launchpad.</p></div><button className="primary" onClick={start}><Icon name="plus"/>Start New Use Case</button></section>
  </main>
}
function YesNo({label,help,value,onChange}:{label:string;help?:string;value:Answer;onChange:(a:Answer)=>void}){return <div className="question"><div><label>{label}</label>{help&&<p>{help}</p>}</div><div className="segments"><button className={value==='yes'?'on':''} onClick={()=>onChange('yes')}>Yes</button><button className={value==='no'?'on':''} onClick={()=>onChange('no')}>No</button><button className={value===''?'on':''} onClick={()=>onChange('')}>Not sure</button></div></div>}
function Choice({title,sub,selected,toggle}:{title:string;sub?:string;selected:boolean;toggle:()=>void}){return <button className={`choice ${selected?'selected':''}`} onClick={toggle}><i>{selected&&<Icon name="check"/>}</i><span><b>{title}</b>{sub&&<small>{sub}</small>}</span></button>}
type Props={form:Form;set:<K extends keyof Form>(k:K,v:Form[K])=>void}
function Heading({step,title,sub,icon}:{step:number;title:string;sub:string;icon:string}){return <div className="step-head"><i><Icon name={icon}/></i><div><p>STEP {step+1} OF 5</p><h2>{title}</h2><span>{sub}</span></div></div>}
function Basics({form:f,set}:Props){return <><Heading step={0} icon="spark" title="Tell us about your ML / Data Science use case" sub="Define the analytical problem and intended outcome. GenAI applications are submitted in the J&J Governance Portal."/><div className="form-grid"><Field label="Use case name *" wide><input value={f.name} onChange={e=>set('name',e.target.value)} placeholder="e.g., Supply Demand Forecast"/><small>Use a working title—you can change it later.</small></Field><Field label="What problem are you trying to solve? *" wide><textarea value={f.summary} onChange={e=>set('summary',e.target.value)} placeholder="Describe the decision, prediction, or analysis this work should improve..."/><small className="count">{f.summary.length} / 500</small></Field><Field label="Business unit *"><select value={f.unit} onChange={e=>set('unit',e.target.value)}><option value="">Select business unit</option><option>MedTech</option><option>Innovative Medicine</option><option>Enterprise</option></select></Field><Field label="Business owner *"><input value={f.owner} onChange={e=>set('owner',e.target.value)} placeholder="Search by name or email"/></Field><Field label="Primary users"><select value={f.audience} onChange={e=>set('audience',e.target.value)}><option value="">Select users</option><option>Data scientists</option><option>Business analysts</option><option>Operational teams</option><option>Research teams</option></select></Field><Field label="Current stage"><select value={f.stage} onChange={e=>set('stage',e.target.value)}><option value="">Select stage</option><option>Idea / discovery</option><option>Experiment</option><option>Pilot</option><option>Production</option></select></Field></div></>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <div className={`field ${wide?'wide':''}`}><label>{label}</label>{children}</div>}
function Data({form:f,set}:Props){return <><Heading step={1} icon="data" title="Data & privacy" sub="Describe the data characteristics that affect risk. Specific sources are selected after approval."/><div className="question-group"><h3>Data classification</h3><p>What categories of information could the application access or process?</p></div><div className="questions"><YesNo label="Will the application process personal information?" help="Information that identifies or could identify an individual." value={f.personal} onChange={v=>set('personal',v)}/><YesNo label="Will it use patient or health information?" help="Includes clinical, diagnosis, treatment, or medical device data." value={f.health} onChange={v=>set('health',v)}/><YesNo label="Will it process employee or workforce information?" value={f.employee} onChange={v=>set('employee',v)}/><YesNo label="Will it use confidential J&J information or intellectual property?" value={f.confidential} onChange={v=>set('confidential',v)}/><YesNo label="Will it use regulated quality, clinical, or safety data?" value={f.regulated} onChange={v=>set('regulated',v)}/></div><div className="question-group"><h3>Data handling</h3><p>How will sensitive information be identified, reused, and transferred?</p></div><div className="questions"><YesNo label="Could personal or health information be directly identifiable?" help="For example: names, IDs, contact details, or linkable records." value={f.identifiable} onChange={v=>set('identifiable',v)}/><YesNo label="Will application data be used to train or fine-tune a model?" value={f.modelTraining} onChange={v=>set('modelTraining',v)}/><YesNo label="Will data be processed outside J&J-controlled systems?" value={f.externalData} onChange={v=>set('externalData',v)}/><YesNo label="Could data cross national or regional boundaries?" value={f.crossBorder} onChange={v=>set('crossBorder',v)}/></div><div className="deferred-note"><Icon name="info"/><div><strong>Data connections come later</strong><span>After initial approval, you’ll choose specific knowledge sources, systems, access roles, and retention settings during solution configuration.</span></div></div></>}
function Capabilities({form:f,set}:Props){const caps=[['Predict outcomes','Estimate a future value or event'],['Classify records','Assign categories or risk groups'],['Forecast trends','Model time-series demand or behavior'],['Detect anomalies','Identify unusual patterns or signals'],['Computer vision','Analyze images or video'],['Statistical analysis','Test hypotheses and quantify relationships']];return <><Heading step={2} icon="spark" title="Modeling approach" sub="What analytical capability does this use case require?"/><Field label="Select all proposed capabilities"><div className="choices two">{caps.map(x=><Choice key={x[0]} title={x[0]} sub={x[1]} selected={f.capabilities.includes(x[0])} toggle={()=>set('capabilities',f.capabilities.includes(x[0])?f.capabilities.filter(v=>v!==x[0]):[...f.capabilities,x[0]])}/>)}</div></Field><div className="autonomy"><label>Decision influence</label><p>How directly will model output affect a business process?</p><div><b>{['','Exploratory','Informational','Advisory','Human-approved action','Automated action'][f.autonomy]}</b><span>{f.autonomy} of 5</span></div><input type="range" min="1" max="5" value={f.autonomy} onChange={e=>set('autonomy',+e.target.value)}/><small><i>Research only</i><i>Direct operational action</i></small></div><div className="questions"><YesNo label="Will model output be exposed outside J&J?" value={f.publicFacing} onChange={v=>set('publicFacing',v)}/></div></>}
function Impact({form:f,set}:Props){return <><Heading step={3} icon="shield" title="Impact & safeguards" sub="Help us understand the consequences of an incorrect output."/><div className="questions"><YesNo label="Could an incorrect response affect patient safety?" value={f.safety} onChange={v=>set('safety',v)}/><YesNo label="Could it affect product quality or a regulated process?" value={f.quality} onChange={v=>set('quality',v)}/><YesNo label="Could it influence a clinical, employment, or other consequential decision?" value={f.decisions} onChange={v=>set('decisions',v)}/><YesNo label="Will a person review outputs before they are acted upon?" value={f.humanReview} onChange={v=>set('humanReview',v)}/><YesNo label="Will prompts, outputs, and actions be recorded for audit?" value={f.audit} onChange={v=>set('audit',v)}/></div></>}
function Review({form:f,risk:r}:{form:Form;risk:Risk}){return <><Heading step={4} icon="check" title="Review your request" sub="Confirm the details and understand the proposed review path."/><div className="review-banner"><b className={r.level.toLowerCase()}>{r.score}</b><div><p>PRELIMINARY CLASSIFICATION</p><h3>{r.level} risk</h3><span>Reviewers make the final determination.</span></div></div><section className="summary"><h3>Application</h3><div><span>Name<strong>{f.name||'Not provided'}</strong></span><span>Business unit<strong>{f.unit||'Not provided'}</strong></span><span className="full">Business need<strong>{f.summary||'Not provided'}</strong></span></div></section><section className="summary"><h3>Proposed review path</h3><div className="route">{r.reviewers.map((x,i)=><span key={x}><b>{i+1}</b><strong>{x}</strong></span>)}</div></section><section className="summary"><h3>Why this classification?</h3><ul>{r.reasons.map(x=><li key={x}><Icon name="info"/>{x}</li>)}</ul></section><label className="attest"><input type="checkbox"/> I confirm the information provided is accurate to the best of my knowledge.</label></>}
function RiskPanel({risk:r}:{risk:Risk}){return <aside className="risk"><div className="risk-title"><i className={r.level.toLowerCase()}><Icon name="shield"/></i><div><p>LIVE RISK PROFILE</p><h3>{r.level} risk</h3></div><b className={r.level.toLowerCase()}>{r.score}/100</b></div><div className="notice"><Icon name="info"/>Preliminary classification based on your answers. This is not an approval decision.</div><section><h4>Risk dimensions</h4>{r.dimensions.map(d=><div className="dimension" key={d.name}><p><span>{d.name}</span><b>{d.value<22?'Low':d.value<50?'Moderate':'High'}</b></p><div><i className={d.value<22?'low':d.value<50?'moderate':'high'} style={{width:`${Math.max(3,d.value)}%`}}/></div></div>)}</section><section><h4>What is driving this?</h4>{r.reasons.slice(0,3).map(x=><p className="reason" key={x}><i/> {x}</p>)}</section><section><h4>Likely reviewers <Pill text={`${r.reviewers.length}`} tone="In review"/></h4><div className="reviewers">{r.reviewers.map(x=><span key={x}>{x}</span>)}</div></section>{r.controls.length>0&&<section className="controls"><h4>Recommended safeguards</h4>{r.controls.map(x=><p key={x}><Icon name="check"/>{x}</p>)}</section>}<button className="learn">How classification works <Icon name="arrow"/></button></aside>}
function Intake({exit,submit}:{exit:()=>void;submit:()=>void}){const[step,setStep]=useState(0),[saved,setSaved]=useState(false),[form,setForm]=useState<Form>(()=>{try{return JSON.parse(localStorage.getItem('ai-draft')||'null')||initial}catch{return initial}});const risk=useMemo(()=>calculate(form),[form]);const set=<K extends keyof Form>(k:K,v:Form[K])=>{setForm(f=>({...f,[k]:v}));setSaved(false)};useEffect(()=>{const t=setTimeout(()=>localStorage.setItem('ai-draft',JSON.stringify(form)),500);return()=>clearTimeout(t)},[form]);const save=()=>{localStorage.setItem('ai-draft',JSON.stringify(form));setSaved(true)};const next=()=>{if(step<4){setStep(s=>s+1);scrollTo(0,0)}else{localStorage.removeItem('ai-draft');submit()}};return <div className="intake"><div className="intake-top"><button onClick={exit}><Icon name="back"/>My applications</button><span>Draft · ML / Data Science use case</span><button className="secondary" onClick={save}><Icon name="save"/>{saved?'Saved':'Save draft'}</button></div><div className="stepper">{stepNames.map((x,i)=><button key={x} className={`${i===step?'active':''} ${i<step?'done':''}`} onClick={()=>i<=step&&setStep(i)}><b>{i<step?<Icon name="check"/>:`0${i+1}`}</b><span>{x}</span>{i<4&&<i/>}</button>)}</div><main className="intake-main"><div className="form-card">{step===0&&<Basics form={form} set={set}/>} {step===1&&<Data form={form} set={set}/>} {step===2&&<Capabilities form={form} set={set}/>} {step===3&&<Impact form={form} set={set}/>} {step===4&&<Review form={form} risk={risk}/>}<div className="form-actions"><button className="secondary" onClick={()=>step?setStep(s=>s-1):exit()}><Icon name="back"/>{step?'Back':'Cancel'}</button><div><span>{step+1} of 5</span><button className="primary" onClick={next}>{step===4?'Submit for review':'Continue'}<Icon name="arrow"/></button></div></div></div><RiskPanel risk={risk}/></main></div>}
function Submitted({home}:{home:()=>void}){return <main className="submitted"><div><Icon name="check"/></div><Pill text="Use case submitted" tone="Approved"/><h1>Your ML / Data Science use case is on its way.</h1><p>Request <b>MLDS-2026-0157</b> has been sent for initial review. We’ll notify you when action is required.</p><section><span>Next step<strong>Business owner review</strong></span><span>Expected response<strong>2–3 business days</strong></span><span>Request owner<strong>Nathan Biyani</strong></span></section><button className="primary" onClick={home}>Return to my applications</button></main>}
export default function IntakeApp(){const[view,setView]=useState<View>(restoredPortalView),[activeApplicationId,setActiveApplicationId]=useState(()=>sessionStorage.getItem('launchpad.active-application')??'AI-2026-0118');useEffect(()=>{try{sessionStorage.setItem(portalViewKey,view)}catch{/* Storage may be unavailable in a restricted browser context. */}},[view]);const selectApplication=(applicationId:string)=>{setActiveApplicationId(applicationId);sessionStorage.setItem('launchpad.active-application',applicationId)};const openLifecycle=(applicationId:string)=>{selectApplication(applicationId);setView('lifecycle')};const home=()=>setView('dashboard'),applications=()=>setView('applications'),start=()=>setView('intake'),agents=()=>setView('agents');return <><Header home={home} applications={applications} active={view==='council'?'council':view==='applications'||view==='lifecycle'?'applications':'developer'}/>{view==='dashboard'&&<DeveloperDashboard start={start} configure={openLifecycle} explore={applications} agents={agents}/>} {view==='agents'&&<AgentCatalog home={home}/>} {view==='applications'&&<UseCaseInventory home={home} start={start} configure={openLifecycle}/>} {view==='lifecycle'&&<LifecycleDetail applicationId={activeApplicationId} back={applications}/>} {view==='intake'&&<Intake exit={applications} submit={()=>setView('submitted')}/>} {view==='submitted'&&<Submitted home={applications}/>} {view==='solution'&&<SolutionBuilder applicationId={activeApplicationId} exit={applications}/>} {view==='council'&&<CouncilWorkspace/>}</>}
